# Generated by Django 3.2.2 on 2021-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('descuento', models.CharField(max_length=3)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
